language: node_js
node_js:
  - "lts/*" # latest LTS Node.js release
install:
  - yarn
script:
  - yarn docs:build
deploy:
  provider: pages
  local_dir: dist/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master